version: 2.1

jobs:
  test:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version:
                - "2.6"
                - "2.7"
                - "3.0"
                - "3.1"
                - "3.2"
