ruby: &ruby
  image: rubylang/ruby:3.0.0-preview1-bionic

version: 2

jobs:
  bundle:
    working_directory: ~/tenios-ruby
    docker:
      - *ruby
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-{{ checksum "Gemfile.lock" }}
            - bundle-
      - run: |
          bundle config --local path vendor/bundle &&
          bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths: [~/tenios-ruby/vendor/bundle]
      - persist_to_workspace:
          root: '~'
          paths: [tenios-ruby]

  rbs_validate:
    working_directory: ~/tenios-ruby
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: bundle exec rbs -I sig validate

  rbs_test:
    working_directory: ~/tenios-ruby
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: bundle exec rbs -I sig test --double-suite rspec --target 'Tenios::Blocks*' --unchecked-class RSpec::Mocks::InstanceVerifyingDouble rake


  rubocop:
    working_directory: ~/tenios-ruby
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: bundle exec rubocop

  tests:
    working_directory: ~/tenios-ruby
    docker:
      - *ruby
    steps:
      - attach_workspace:
          at: '~'
      - run: |
          bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - bundle
      - rubocop:
          requires: [bundle]
      - tests:
          requires: [bundle]
      - rbs_validate:
          requires: [bundle]
      - rbs_test:
          requires: [rbs_validate]
