module Tenios
  class Blocks
    class Announcement
      BLOCK_TYPE: String

      def initialize: (announcement: String announcement, ?standard: bool standard) -> Announcement

      def as_json: () -> { blockType: String, standardAnnouncement: TrueClass | FalseClass, announcementName: String }
    end
  end
end
