module Tenios
  class Blocks
    class CallSettings
      BLOCK_TYPE: ::String

      def initialize: (forward_ani: untyped forward_ani) -> untyped

      def as_json: () -> { blockType: untyped, forwardAni: untyped }
    end
  end
end
