module Tenios
  class Blocks
    class CallSettings
      BLOCK_TYPE: String

      def initialize: (forward_ani: String forward_ani) -> CallSettings

      def as_json: () -> { blockType: String, forwardAni: String }
    end
  end
end
