module Tenios
  class Blocks
    class CollectSpeech
      BLOCK_TYPE: ::String

      def initialize: (announcement: untyped announcement, missing_input_announcement: untyped missing_input_announcement, language: untyped language, variable: untyped variable, max_tries: untyped max_tries) -> untyped

      def as_json: () -> { blockType: untyped, standardAnnouncement: ::FalseClass, announcementName: untyped, standardMissingInputAnnouncement: ::FalseClass, missingInputAnnouncementName: untyped, language: untyped, variableName: untyped, maxTries: untyped }
    end
  end
end
