module Tenios
  class Blocks
    class CollectDigits
      BLOCK_TYPE: String

      VARIABLE_REGEX: Regexp

      TERMINATORS: Array[String]

      def initialize: (
        announcement: String announcement,
        standard_announcement: (TrueClass | FalseClass) standard_announcement,
        error_announcement: String error_announcement,
        standard_error_announcement: (TrueClass | FalseClass) standard_error_announcement,
        variable: String variable,
        min_digits: Integer min_digits,
        max_digits: Integer max_digits,
        terminator: String terminator,
        max_tries: Integer max_tries,
        timeout: Integer timeout
      ) -> CollectDigits

      def as_json: () -> Hash[Symbol, String | Integer | (TrueClass | FalseClass)]

      def validate!: () -> void
    end
  end
end
