module Tenios
  class Blocks
    class CollectSpeech
      BLOCK_TYPE: String

      def initialize: (
        announcement: String announcement,
        missing_input_announcement: String missing_input_announcement,
        language: String language,
        variable: String variable,
        max_tries: Integer max_tries
      ) -> CollectSpeech

      def as_json: () -> {
        blockType: String,
        standardAnnouncement: FalseClass,
        announcementName: String,
        standardMissingInputAnnouncement: FalseClass,
        missingInputAnnouncementName: String,
        language: String,
        variableName: String,
        maxTries: Integer
      }
    end
  end
end
