module Tenios
  class Blocks
    class RoutingPlan
      BLOCK_TYPE: ::String

      def initialize: (routing_plan: untyped routing_plan) -> untyped

      def as_json: () -> { blockType: untyped, routingplanName: untyped }
    end
  end
end
