module Tenios
  class Blocks
    class Say
      BLOCK_TYPE: ::String

      def initialize: (text: untyped text, voice: untyped voice, ssml: untyped ssml) -> untyped

      def as_json: () -> { blockType: untyped, text: untyped, voiceName: untyped, useSsml: untyped }

      def validate!: () -> untyped
    end
  end
end
